### ISSUE TITLE
Configuration should go to a separate include file

### ISSUE THREAD

**Issue by wzurborg** [sjau/le2ispc#3]
The config above the "dragons" should go into a separate include file *config.inc.php*, such that the update is easier for the users. I have implemented that but it would not work if people copied the script to /usr/bin as per instructions, so I am not pushing it yet. Do you have any preference where to put the config file?

**Comment by sjau** [comment]
well, once the script works, it shouldn't require update anymore.

Since the default LE client needs root access (there's one without root), I guess /root/.config/le2isp.conf.php would be an option or maybe /etc/le2ispconfig/ or maybe /etc/letsencrypt/le2isp.conf.php

Not really sure what a good place is.

**Comment by wzurborg** [comment]
> once the script works, it shouldn't require update anymore.

you always think that in the beginning :smile: 

But ok multiple files seem to require a proper installer or packaging, so I'll leave everything in one file for now.

**Comment by sjau** [comment]
well, that script won't be in use forever anyway since Till is planing to add proper LE support to ISPC. For the time being I'm fine with this hackjob :)

**Comment by sjau** [comment]
so, finally fixed that here: https://github.com/sjau/le2ispc/commit/cb4f2ce3a8c0263eddefc2daa854fb162dec5039
